/**
 * Error Codes
 * 
 * Structured error codes for programmatic error handling
 */
export enum ErrorCode {
  // Authentication (AUTH_XXX)
  AUTH_TOKEN_INVALID = 'AUTH_001',
  AUTH_TOKEN_EXPIRED = 'AUTH_002',
  AUTH_UNAUTHORIZED = 'AUTH_003',
  AUTH_FORBIDDEN = 'AUTH_004',

  // Social Accounts (ACCOUNT_XXX)
  ACCOUNT_NOT_FOUND = 'ACCOUNT_001',
  ACCOUNT_TOKEN_EXPIRED = 'ACCOUNT_002',
  ACCOUNT_INVALID_PLATFORM = 'ACCOUNT_003',
  ACCOUNT_NOT_OWNED_BY_USER = 'ACCOUNT_004',
  ACCOUNT_INACTIVE = 'ACCOUNT_005',

  // Scheduled Posts (POST_XXX)
  POST_NOT_FOUND = 'POST_001',
  POST_SCHEDULE_INVALID = 'POST_002',
  POST_MEDIA_INVALID = 'POST_003',
  POST_PLATFORM_ERROR = 'POST_004',
  POST_ALREADY_PUBLISHED = 'POST_005',
  POST_CANNOT_EDIT = 'POST_006',

  // Rate Limiting (RATE_XXX)
  RATE_LIMIT_EXCEEDED = 'RATE_001',

  // External APIs (EXTERNAL_XXX)
  EXTERNAL_API_ERROR = 'EXTERNAL_001',
  EXTERNAL_API_TIMEOUT = 'EXTERNAL_002',
  EXTERNAL_API_RATE_LIMIT = 'EXTERNAL_003',
  EXTERNAL_API_UNAUTHORIZED = 'EXTERNAL_004',

  // Validation (VALIDATION_XXX)
  VALIDATION_FAILED = 'VALIDATION_001',
  VALIDATION_INVALID_INPUT = 'VALIDATION_002',

  // Database (DB_XXX)
  DB_CONNECTION_ERROR = 'DB_001',
  DB_QUERY_ERROR = 'DB_002',
  DB_TRANSACTION_ERROR = 'DB_003',

  // Queue (QUEUE_XXX)
  QUEUE_JOB_FAILED = 'QUEUE_001',
  QUEUE_JOB_TIMEOUT = 'QUEUE_002',

  // Circuit Breaker (CIRCUIT_XXX)
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_001',

  // General (GENERAL_XXX)
  GENERAL_INTERNAL_ERROR = 'GENERAL_001',
  GENERAL_NOT_FOUND = 'GENERAL_002',
  GENERAL_BAD_REQUEST = 'GENERAL_003',
}
